from pwdlib import PasswordHash
from datetime import datetime, timedelta, timezone
import jwt
import secrets
import string
import hashlib
from typing import Any

from config import SECRET_KEY, ACCESS_TOKEN_EXPIRE_MINUTES

pass_hash = PasswordHash.recommended()

def validation_password(password: str) -> str:
    """EN: Validate a raw password against the current password policy.

    The function trims outer whitespace and checks basic strength rules:
    minimum length, at least one special symbol, one uppercase letter,
    and one digit.

    Args:
        password: Raw password entered by the user.

    Returns:
        Normalized password string after validation.

    Raises:
        ValueError: If the password does not satisfy the policy.

    RU: Проверяет сырой пароль на соответствие текущей парольной политике.

    Функция убирает внешние пробелы и проверяет базовые правила сложности:
    минимальную длину, наличие спецсимвола, одной заглавной буквы
    и одной цифры.

    Аргументы:
        password: пароль, который ввёл пользователь.

    Возвращает:
        Нормализованную строку пароля после успешной проверки.

    Исключения:
        ValueError: Если пароль не проходит проверку по правилам.
    """


    password = password.strip()

    if len(password) < 8:
        raise ValueError("Пароль слишком короткий")

    if not any(x in password for x in "@`~!?$#*&^()"):
        raise ValueError("Пароль должен содержать спецсимвол")

    if not any(char.isupper() for char in password):
        raise ValueError("Пароль должен содержать хотя бы одну заглавную букву")

    if not any(char.isdigit() for char in password):
        raise ValueError("Пароль должен содержать цифры")

    return password

def get_password_hash(password: str) -> str:
    """EN: Validate a password and return its secure hash representation.

    Args:
        password: Raw password string before hashing.

    Returns:
        Password hash generated by ``pwdlib``.

    RU: Проверяет пароль и возвращает его безопасный хеш.

    Аргументы:
        password: сырой пароль до хеширования.

    Возвращает:
        Хеш пароля, созданный через ``pwdlib``.
    """

    
    password = validation_password(password)
    return pass_hash.hash(password)

def verify_password(password: str, password_hash: str) -> bool:
    """EN: Compare a raw password with a stored password hash.

    Args:
        password: Raw password provided for verification.
        password_hash: Stored hash from the database.

    Returns:
        ``True`` if the password matches the hash, otherwise ``False``.

    RU: Сравнивает сырой пароль с сохранённым хешем пароля.

    Аргументы:
        password: пароль, который пришёл на проверку.
        password_hash: хеш пароля, сохранённый в базе данных.

    Возвращает:
        ``True``, если пароль совпадает с хешем, иначе ``False``.
    """
    try:
        return pass_hash.verify(password, password_hash)
    except Exception:
        
        return False


def create_access_token(user_id: int, role: Any) -> str:
    """EN: Create a short-lived JWT access token for the authenticated user.

    Args:
        user_id: Identifier of the authenticated user.
        role: User role object whose value is written into the JWT payload.

    Returns:
        Encoded JWT access token string.

    RU: Создаёт короткоживущий JWT access token для аутентифицированного пользователя.

    Аргументы:
        user_id: идентификатор аутентифицированного пользователя.
        role: объект роли пользователя, значение которого попадёт в payload JWT.

    Возвращает:
        Закодированную строку JWT access token.
    """

  
    now = datetime.now(timezone.utc)

    payload = {
        "sub": str(user_id),        # стандарт JWT
        "user_id": user_id,
        "role": role.value,
        "iat": now,                # когда выдан
        "exp": now + timedelta(minutes=ACCESS_TOKEN_EXPIRE_MINUTES),
    }

    return jwt.encode(payload, SECRET_KEY, algorithm="HS256")


def create_refresh_token():
    """EN: Generate a random refresh token string.

    Returns:
        Random token composed of latin letters and digits.

    RU: Генерирует случайную строку refresh token.

    Возвращает:
        Случайный токен, составленный из латинских букв и цифр.
    """

    alphabet = string.ascii_letters + string.digits
    return "".join(secrets.choice(alphabet) for _ in range(40))


def create_reset_token() -> str:
    """EN: Generate a one-time password reset token string.

    The current implementation intentionally reuses the same random generation
    strategy as refresh tokens, but keeps a separate function so reset-token
    logic can evolve independently later.

    Returns:
        Random reset token string.

    RU: Генерирует одноразовый токен для сброса пароля.

    Текущая реализация специально использует тот же способ генерации случайной строки,
    что и refresh token, но вынесена в отдельную функцию, чтобы дальше логику
    reset token можно было развивать независимо.

    Возвращает:
        Случайную строку reset token.
    """

    alphabet = string.ascii_letters + string.digits
    return "".join(secrets.choice(alphabet) for _ in range(40))


def hash_token(token: str) -> str:
    """EN: Return the SHA-256 hash of a token string.

    Args:
        token: Raw token value that should not be stored directly.

    Returns:
        Hexadecimal SHA-256 digest.

    RU: Возвращает SHA-256 хеш для строки токена.

    Аргументы:
        token: сырой токен, который не нужно хранить в базе напрямую.

    Возвращает:
        Шестнадцатеричное представление SHA-256 хеша.
    """

    return hashlib.sha256(token.encode()).hexdigest()

def decode_access_token(token: str) -> dict[str, Any]:
    """EN: Decode and validate a JWT access token.

    Args:
        token: Encoded JWT access token string.

    Returns:
        Decoded payload dictionary.

    Raises:
        ValueError: If the token is expired, invalid, or has an unexpected payload.

    RU: Декодирует и валидирует JWT access token.

    Аргументы:
        token: закодированная строка JWT access token.

    Возвращает:
        Словарь с декодированным payload.

    Исключения:
        ValueError: Если токен истёк, повреждён или содержит некорректный payload.
    """

    try:
        payload = jwt.decode(token, SECRET_KEY, algorithms=["HS256"])
    except jwt.ExpiredSignatureError:
        # токен истёк
        raise ValueError("Токен истёк")
    except jwt.InvalidTokenError:
        # любая другая ошибка JWT (подделка, мусор и т.д.)
        raise ValueError("Неверный токен")

    # дополнительная проверка содержимого
    if "user_id" not in payload or "role" not in payload:
        raise ValueError("Некорректный payload")

    return payload
    
    
     
