from pwdlib import PasswordHash
from datetime import datetime, timedelta, timezone
import jwt
import secrets
import string
import hashlib
from config import secret_key as SECRET_KEY



def validation_password(password: str):
    """EN: Validate a raw password against the current password policy.

    The function trims outer whitespace and checks basic strength rules:
    minimum length, at least one special symbol, one uppercase letter,
    and one digit.

    Args:
        password: Raw password entered by the user.

    Returns:
        Normalized password string after validation.

    Raises:
        ValueError: If the password does not satisfy the policy.

    RU: Проверяет сырой пароль на соответствие текущей парольной политике.

    Функция убирает внешние пробелы и проверяет базовые правила сложности:
    минимальную длину, наличие спецсимвола, одной заглавной буквы
    и одной цифры.

    Аргументы:
        password: пароль, который ввёл пользователь.

    Возвращает:
        Нормализованную строку пароля после успешной проверки.

    Исключения:
        ValueError: Если пароль не проходит проверку по правилам.
    """

    password = password.strip()
    if len(password) < 8:
        raise ValueError ('Пароль слишком короткий')
    if not any(x in password for x in "@`~!?$#*&^()"):
        raise ValueError('Пароль должен содержать спецсимвол')
    if not any(char.isupper() for char in password):
        raise ValueError("Пароль должен содержать хотя бы одну заглавную букву")
    if not any(char.isdigit() for char in password):
        raise ValueError("Пароль должен содержать цифры")
    return password

def get_password_hash(password):
    """EN: Validate a password and return its secure hash representation.

    Args:
        password: Raw password string before hashing.

    Returns:
        Password hash generated by ``pwdlib``.

    RU: Проверяет пароль и возвращает его безопасный хеш.

    Аргументы:
        password: сырой пароль до хеширования.

    Возвращает:
        Хеш пароля, созданный через ``pwdlib``.
    """

    password = validation_password(password)
    password_hash = PasswordHash.recommended()
    hash_ = password_hash.hash(password)
    return hash_

def verify_password(password,password_hash):
    """EN: Compare a raw password with a stored password hash.

    Args:
        password: Raw password provided for verification.
        password_hash: Stored hash from the database.

    Returns:
        ``True`` if the password matches the hash, otherwise ``False``.

    RU: Сравнивает сырой пароль с сохранённым хешем пароля.

    Аргументы:
        password: пароль, который пришёл на проверку.
        password_hash: хеш пароля, сохранённый в базе данных.

    Возвращает:
        ``True``, если пароль совпадает с хешем, иначе ``False``.
    """

    pass_hash = PasswordHash.recommended()
    valid = pass_hash.verify(password, password_hash)
    return valid

def create_access_token(user_id,role):
    """EN: Create a short-lived JWT access token for the authenticated user.

    Args:
        user_id: Identifier of the authenticated user.
        role: User role object whose value is written into the JWT payload.

    Returns:
        Encoded JWT access token string.

    RU: Создаёт короткоживущий JWT access token для аутентифицированного пользователя.

    Аргументы:
        user_id: идентификатор аутентифицированного пользователя.
        role: объект роли пользователя, значение которого попадёт в payload JWT.

    Возвращает:
        Закодированную строку JWT access token.
    """

    expires_at = datetime.now(timezone.utc) + timedelta(minutes=15)
    payload = {
    "user_id": user_id,
    "role": role.value,
    "exp": expires_at,
}
    secret_key = SECRET_KEY

    token = jwt.encode(payload, secret_key, algorithm="HS256")
    return token


def create_refresh_token():
    """EN: Generate a random refresh token string.

    Returns:
        Random token composed of latin letters and digits.

    RU: Генерирует случайную строку refresh token.

    Возвращает:
        Случайный токен, составленный из латинских букв и цифр.
    """

    alphabet = string.ascii_letters + string.digits
    refresh_token = ''.join(secrets.choice(alphabet) for i in range(20))
    
    return refresh_token



def hash_token(token):
    """EN: Return the SHA-256 hash of a token string.

    Args:
        token: Raw token value that should not be stored directly.

    Returns:
        Hexadecimal SHA-256 digest.

    RU: Возвращает SHA-256 хеш для строки токена.

    Аргументы:
        token: сырой токен, который не нужно хранить в базе напрямую.

    Возвращает:
        Шестнадцатеричное представление SHA-256 хеша.
    """

    return hashlib.sha256(token.encode()).hexdigest()

